baseURL = 'https://h2w2-life.github.com/'
languageCode = 'en-us'
title = 'H2W2.Life'

# https://ox-hugo.scripter.co/doc/quick-start/
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.goldmark.renderer]
  unsafe = true
