baseURL = 'https://h2w2-life.github.io/blog/'
languageCode = 'en-us'
title = 'h2w2.life'

# https://ox-hugo.scripter.co/doc/quick-start/
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.goldmark.renderer]
  unsafe = true

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/
[params]
  comments = true
